name: Deploy documentation ⚙️

on:
  push:
    branches:
      - main
    paths:
      - 'workshop/content/**'

jobs:
  build:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install requirements 📦
        run: |
          python -m pip install --upgrade pip
          pip install -r workshop/content/requirements.txt
      - name: Build site 📦
        run: |
          cd workshop/content
          zensical build --clean --strict
          zensical build --strict --config-file zensical.pt.toml
          mv site /tmp/
      - name: checkout gh-pages branch
        uses: actions/checkout@master
        with:
          ref: gh-pages
      - name: Deploy to GitHub Pages 📦
        run: |
          git checkout gh-pages
          git config --global user.email "tomkralidis@gmail.com"
          git config --global user.name "Tom Kralidis"
          ls | grep -v ".nojekyll"| xargs rm -fr
          mv -f /tmp/site/* .
          git add .
          git commit -am "update website via GitHub Actions"
          git push
